#I need to separate each quote with a comma ","

Wishes = ["Wishing you a day as special as you are. Happy birthday!"
"May your birthday be the start of a year filled with good luck, good health, and much happiness."
"Another year, another reason to celebrate the awesome person you are. Happy birthday!"
"As you blow out the candles, may all your wishes come true. Happy birthday!"
"Cheers to you on your birthday! May your day be filled with love, laughter, and the company of good friends."
"Happy birthday! May the coming year bring you endless joy and fulfillment."
"On your special day, take a moment to reflect on the wonderful journey that has brought you here. Happy birthday!"
"May your birthday be filled with moments that make you smile and memories that last a lifetime."
"Here's to another year of laughter, joy, and incredible adventures. Happy birthday!"
"Wishing you a day filled with love, surrounded by those who mean the most. Happy birthday!"
"As you celebrate another year of life, may each moment be as special as you are. Happy birthday!"
"May the coming year be filled with success, happiness, and all the things you've been dreaming of. Happy birthday!"
"Happy birthday to someone who makes the world a brighter place just by being in it."
"May your birthday be the beginning of a year filled with new accomplishments and beautiful memories."
"Cheers to a day that's as amazing as you are! Happy birthday!"
"On your special day, I hope you feel surrounded by love and warmth. Happy birthday!"
"Another year older, wiser, and more fabulous! Happy birthday!"
"May your birthday be the start of a year filled with new opportunities and great achievements. Happy birthday!"
"Wishing you a day filled with surprises, laughter, and all the things that make you smile. Happy birthday!"
"Here's to celebrating you on your special day. May it be filled with joy and everything you love. Happy birthday!"
"As the candles multiply, may your happiness multiply even more. Happy birthday!"
"May your birthday be the perfect blend of fun, joy, and all the things that make you happy."
"On your birthday, may you be surrounded by people who love and appreciate you. Happy birthday!"
"Happy birthday! May your day be as bright and beautiful as your smile."
"Wishing you a day that's as sweet and delightful as you are. Happy birthday!"
"May this year be filled with exciting adventures and wonderful surprises. Happy birthday!"
"Happy birthday to someone who brings sunshine into the lives of everyone around them."
"May your birthday be filled with love, laughter, and all the things that make life beautiful. Happy birthday!"
"Here's to another year of incredible accomplishments and amazing moments. Happy birthday!"
"Wishing you a day that's as special and unique as you are. Happy birthday!"
"May your birthday be the start of a year filled with new opportunities and exciting adventures. Happy birthday!"
"Happy birthday! May the year ahead be even more amazing than the one before."
"On your special day, may you be surrounded by love, joy, and all the things that make life wonderful."
"May your birthday be the beginning of a year filled with happy moments and wonderful memories."
"Happy birthday to someone who deserves all the love and happiness in the world."
"Wishing you a day that's as bright and beautiful as your smile. Happy birthday!"
"Cheers to another year of laughter, joy, and unforgettable moments. Happy birthday!"
"May your birthday be the start of a year filled with exciting adventures and incredible accomplishments. Happy birthday!"
"Happy birthday! May your day be as special and amazing as you are."
"Wishing you a day filled with love, laughter, and all the things that make life beautiful. Happy birthday!"
"On your birthday, may you be surrounded by the people who make your heart happy. Happy birthday!"
"Another year, another reason to celebrate the incredible person you are. Happy birthday!"
"May your birthday be the beginning of a year filled with new opportunities and exciting adventures. Happy birthday!"
"Happy birthday! May your day be filled with love, laughter, and the company of good friends."
"Cheers to another year of laughter, joy, and unforgettable moments. Happy birthday!"
"Wishing you a day as special and wonderful as you are. Happy birthday!"
"May your birthday be the start of a year filled with new accomplishments and beautiful memories. Happy birthday!"
"Happy birthday to someone who makes the world a better place just by being in it."
"May your birthday be filled with love, joy, and all the things that make life beautiful. Happy birthday!"
"Here's to celebrating the amazing person you are on your special day. Happy birthday!"
"On your birthday, may you be surrounded by the people who love and appreciate you. Happy birthday!"
"Wishing you a day filled with love, laughter, and all the things that make life beautiful. Happy birthday!"
"Happy birthday! May your day be as bright and beautiful as your smile."
"May your birthday be the beginning of a year filled with new opportunities and exciting adventures. Happy birthday!"
"Cheers to another year of incredible accomplishments and amazing moments. Happy birthday!"
"Happy birthday! May the year ahead be even more amazing than the one before."
"On your special day, may you be surrounded by love, joy, and all the things that make life wonderful."
"May your birthday be the start of a year filled with happy moments and wonderful memories. Happy birthday!"
"Happy birthday to someone who deserves all the love and happiness in the world."
"Wishing you a day that's as bright and beautiful as your smile. Happy birthday!"
"Cheers to another year of laughter, joy, and unforgettable moments. Happy birthday!"
"May your birthday be the beginning of a year filled with exciting adventures and incredible accomplishments. Happy birthday!"
"Happy birthday! May your day be as special and amazing as you are."
"Wishing you a day filled with love, laughter, and all the things that make life beautiful. Happy birthday!"
"On your birthday, may you be surrounded by the people who make your heart happy. Happy birthday!"
"Another year, another reason to celebrate the incredible person you are. Happy birthday!"
"May your birthday be the start of a year filled with new opportunities and exciting adventures. Happy birthday!"
"Happy birthday! May your day be filled with love, laughter, and the company of good friends."
"Cheers to another year of laughter, joy, and unforgettable moments. Happy birthday!"
"Wishing you a day as special and wonderful as you are. Happy birthday!"
"May your birthday be the beginning of a year filled with new accomplishments and beautiful memories. Happy birthday!"
"Happy birthday to someone who makes the world a better place just by being in it."
"May your birthday be filled with love, joy, and all the things that make life beautiful. Happy birthday!"
"Here's to celebrating the amazing person you are on your special day. Happy birthday!"
"On your birthday, may you be surrounded by the people who love and appreciate you. Happy birthday!"
"Wishing you a day filled with love, laughter, and all the things that make life beautiful. Happy birthday!"
"Happy birthday! May your day be as bright and beautiful as your smile."
"May your birthday be the beginning of a year filled with new opportunities and exciting adventures. Happy birthday!"
"Cheers to another year of incredible accomplishments and amazing moments. Happy birthday!"
"Happy birthday! May the year ahead be even more amazing than the one before."
"On your special day, may you be surrounded by love, joy, and all the things that make life wonderful."
"May your birthday be the start of a year filled with happy moments and wonderful memories. Happy birthday!"
"Happy birthday to someone who deserves all the love and happiness in the world."
"Wishing you a day that's as bright and beautiful as your smile. Happy birthday!"
"Cheers to another year of laughter, joy, and unforgettable moments. Happy birthday!"
"May your birthday be the beginning of a year filled with exciting adventures and incredible accomplishments. Happy birthday!"
"Happy birthday! May your day be as special and amazing as you are."
"Wishing you a day filled with love, laughter, and all the things that make life beautiful. Happy birthday!"
"On your birthday, may you be surrounded by the people who make your heart happy. Happy birthday!"
"Another year, another reason to celebrate the incredible person you are. Happy birthday!"
"May your birthday be the start of a year filled with new opportunities and exciting adventures. Happy birthday!"
"Happy birthday! May your day be filled with love, laughter, and the company of good friends."
"Cheers to another year of laughter, joy, and unforgettable moments. Happy birthday!"
"Wishing you a day as special and wonderful as you are. Happy birthday!"
"May your birthday be the beginning of a year filled with new accomplishments and beautiful memories. Happy birthday!"
"Happy birthday to someone who makes the world a better place just by being in it."
"May your birthday be filled with love, joy, and all the things that make life beautiful. Happy birthday!"
"Here's to celebrating the amazing person you are on your special day. Happy birthday!"
"On your birthday, may you be surrounded by the people who love and appreciate you. Happy birthday!"
"Wishing you a day filled with love, laughter, and all the things that make life beautiful. Happy birthday!"

]